package com.bennyjon.aui.core.plugin

import com.bennyjon.aui.core.model.AuiBlock
import kotlin.reflect.KClass

/**
 * Central registry of all AUI plugins — both component plugins and action plugins.
 *
 * The host app builds **one** registry and passes it to both the renderer
 * (for rendering custom components and handling actions) and
 * [AuiCatalogPrompt][com.bennyjon.aui.core.AuiCatalogPrompt]
 * (for including plugin schemas in the AI system prompt). Single instance,
 * single source of truth.
 *
 * Example:
 * ```kotlin
 * val registry = AuiPluginRegistry().registerAll(
 *     ProductReviewPlugin,           // component plugin
 *     NavigateActionPlugin(navCtrl), // action plugin
 *     OpenUrlActionPlugin(context),  // action plugin
 * )
 *
 * // Pass to renderer
 * AuiRenderer(json = auiJson, pluginRegistry = registry, onFeedback = { ... })
 *
 * // Pass to prompt generator
 * val systemPrompt = AuiCatalogPrompt.generate(pluginRegistry = registry)
 * ```
 *
 * Duplicate handling: if a newly registered plugin has the same
 * [AuiPlugin.slotKey] as an existing one, the old plugin is removed
 * (last-registered wins).
 */
class AuiPluginRegistry {
    private val plugins = mutableListOf<AuiPlugin>()

    /**
     * Wire type strings allowed in the AI prompt. `null` means no filter — full catalog
     * is advertised (default behavior).
     */
    private var allowedPromptTypes: Set<String>? = null

    /**
     * Register a plugin. If another plugin with the same [AuiPlugin.slotKey]
     * is already registered, it is replaced (last-registered wins).
     *
     * @return this registry for fluent chaining.
     */
    fun register(plugin: AuiPlugin): AuiPluginRegistry {
        plugins.removeAll { it.slotKey == plugin.slotKey }
        plugins.add(plugin)
        return this
    }

    /**
     * Register multiple plugins at once. Each plugin follows the same
     * deduplication rules as [register].
     *
     * @return this registry for fluent chaining.
     */
    fun registerAll(vararg newPlugins: AuiPlugin): AuiPluginRegistry {
        newPlugins.forEach { register(it) }
        return this
    }

    /**
     * All registered plugins, in registration order.
     *
     * Used by [AuiCatalogPrompt][com.bennyjon.aui.core.AuiCatalogPrompt]
     * to read [AuiPlugin.promptSchema] from every plugin regardless of type.
     */
    fun allPlugins(): List<AuiPlugin> = plugins.toList()

    /**
     * Look up an action plugin by its [AuiActionPlugin.action] name.
     *
     * @return the matching plugin, or `null` if no action plugin is registered for [action].
     */
    fun actionPlugin(action: String): AuiActionPlugin? =
        plugins.filterIsInstance<AuiActionPlugin>().find { it.action == action }

    /** All registered action plugins. */
    fun allActionPlugins(): List<AuiActionPlugin> =
        plugins.filterIsInstance<AuiActionPlugin>()

    /**
     * Restricts which built-in block types are advertised in the AI system prompt
     * generated by [AuiCatalogPrompt][com.bennyjon.aui.core.AuiCatalogPrompt].
     *
     * Does NOT affect rendering — the block renderer renders all block types regardless
     * of this filter. This ensures old conversations with previously-advertised types
     * continue to render correctly after the filter is applied.
     *
     * Plugin component types are always advertised if registered; this filter applies
     * to built-in types only.
     *
     * Default (no call): full built-in catalog is advertised.
     *
     * @param types The [AuiBlock] subclasses to advertise. [AuiBlock.Unknown] is not
     *   a valid argument and will throw [IllegalArgumentException].
     * @return this registry for fluent chaining.
     */
    fun includeInPrompt(vararg types: KClass<out AuiBlock>): AuiPluginRegistry {
        allowedPromptTypes = types.map { klass ->
            BLOCK_TYPE_MAP[klass] ?: throw IllegalArgumentException(
                "${klass.simpleName} is not a known built-in AuiBlock subclass. " +
                "Do not pass AuiBlock.Unknown, and make sure BLOCK_TYPE_MAP is up to date."
            )
        }.toSet()
        return this
    }

    /**
     * Returns true if [wireType] should be included in the generated AI prompt.
     * Always returns true when no [includeInPrompt] filter has been set.
     * Internal — used by [AuiCatalogPrompt][com.bennyjon.aui.core.AuiCatalogPrompt] only.
     */
    internal fun isAllowedInPrompt(wireType: String): Boolean {
        return allowedPromptTypes?.contains(wireType) ?: true
    }

    companion object {
        /** An empty registry with no plugins registered. */
        val Empty = AuiPluginRegistry()

        /**
         * Single source of truth for built-in wire type strings.
         * Add new built-in types here when implemented.
         * [AuiBlock.Unknown] is intentionally excluded — it is not a real block type
         * and must not appear in [includeInPrompt] calls.
         */
        internal val BLOCK_TYPE_MAP: Map<KClass<out AuiBlock>, String> = mapOf(
            AuiBlock.Text::class               to "text",
            AuiBlock.Heading::class            to "heading",
            AuiBlock.Caption::class            to "caption",
            AuiBlock.FileContent::class        to "file_content",
            AuiBlock.Chart::class              to "chart",
            AuiBlock.Table::class              to "table",
            AuiBlock.ButtonPrimary::class      to "button_primary",
            AuiBlock.ButtonSecondary::class    to "button_secondary",
            AuiBlock.QuickReplies::class       to "quick_replies",
            AuiBlock.ChipSelectSingle::class   to "chip_select_single",
            AuiBlock.ChipSelectMulti::class    to "chip_select_multi",
            AuiBlock.RadioList::class          to "radio_list",
            AuiBlock.CheckboxList::class       to "checkbox_list",
            AuiBlock.InputTextSingle::class    to "input_text_single",
            AuiBlock.InputSlider::class        to "input_slider",
            AuiBlock.InputRatingStars::class   to "input_rating_stars",
            AuiBlock.Divider::class            to "divider",
            AuiBlock.StepperHorizontal::class  to "stepper_horizontal",
            AuiBlock.ProgressBar::class        to "progress_bar",
            AuiBlock.BadgeInfo::class          to "badge_info",
            AuiBlock.BadgeSuccess::class       to "badge_success",
            AuiBlock.BadgeWarning::class       to "badge_warning",
            AuiBlock.BadgeError::class         to "badge_error",
            AuiBlock.StatusBannerInfo::class    to "status_banner_info",
            AuiBlock.StatusBannerSuccess::class to "status_banner_success",
            AuiBlock.StatusBannerWarning::class to "status_banner_warning",
            AuiBlock.StatusBannerError::class   to "status_banner_error",
        )
    }
}
